version: 2
updates:
  - package-ecosystem: devcontainers
    directory: /
    commit-message:
      prefix: "build: "
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: "ci: "
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: cargo
    directory: /
    commit-message:
      prefix: "chore: "
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
