[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0-rc.1"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/eitsupi/r-documentation-rs"

[workspace.dependencies]
thiserror = "2"
rd-ast = { version = "0.1.0-rc.1", path = "crates/rd-ast" }
rd-rds = { version = "0.1.0-rc.1", path = "crates/rd-rds" }
rd-source = { version = "0.1.0-rc.1", path = "crates/rd-source" }
rd-writer = { version = "0.1.0-rc.1", path = "crates/rd-writer" }
flate2 = "1"
xz2 = "0.1"
bzip2 = "0.6"
ruzstd = "0.8.3"
